# Generated by Django 5.0.6 on 2024-07-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stockid", models.CharField(max_length=20, unique=True)),
                ("abbreviation", models.CharField(max_length=50)),
                ("url", models.URLField()),
                ("industryname", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "company",
            },
        ),
    ]
