# Generated by Django 5.0.6 on 2024-09-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mylab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField(max_length=500)),
                ("content", models.TextField()),
                ("source", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "news",
            },
        ),
    ]
