# Generated by Django 5.0.6 on 2024-09-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mywater", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song", models.TextField()),
                ("singer", models.TextField()),
                ("last_modify_date", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "music",
            },
        ),
    ]
