# Generated by Django 5.0.6 on 2024-10-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mywater", "0002_music"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Music",
        ),
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
