# Generated by Django 5.1.3 on 2025-01-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=255)),
                (
                    "region",
                    models.CharField(
                        choices=[("國內", "國內"), ("國外", "國外")],
                        default="未知",
                        max_length=10,
                    ),
                ),
                ("cover", models.URLField(blank=True, max_length=500, null=True)),
                ("image", models.URLField(blank=True, max_length=500, null=True)),
                ("link", models.URLField(max_length=500)),
                ("content", models.TextField()),
                ("source", models.CharField(max_length=100)),
                ("author", models.CharField(default="", max_length=100)),
                ("date", models.DateField()),
                ("recent_update", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "disaster",
                    models.CharField(
                        choices=[
                            ("乾旱", "乾旱"),
                            ("旱災", "旱災"),
                            ("豪雨", "豪雨"),
                            ("大雨", "大雨"),
                            ("水災", "水災"),
                            ("洪水", "洪水"),
                            ("颱風", "颱風"),
                            ("颶風", "颶風"),
                            ("氣旋", "氣旋"),
                            ("暴雨", "暴雨"),
                            ("淹水", "淹水"),
                            ("地震", "地震"),
                            ("海嘯", "海嘯"),
                            ("火山爆發", "火山爆發"),
                            ("土石流", "土石流"),
                            ("山體滑坡", "山體滑坡"),
                            ("未知", "未知"),
                        ],
                        default="未知",
                        max_length=50,
                    ),
                ),
                ("overview", models.TextField(blank=True, null=True)),
                ("daily_records", models.JSONField(blank=True, null=True)),
                ("links", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "news",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_code", models.CharField(max_length=10, unique=True)),
                ("B", models.TextField()),
                ("P", models.TextField()),
                ("C", models.TextField()),
            ],
            options={
                "db_table": "stock",
            },
        ),
        migrations.CreateModel(
            name="StockMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="股票代號"
                    ),
                ),
                (
                    "毛利率",
                    models.FloatField(blank=True, null=True, verbose_name="毛利率"),
                ),
                (
                    "營業利益率",
                    models.FloatField(blank=True, null=True, verbose_name="營業利益率"),
                ),
                (
                    "淨利率",
                    models.FloatField(blank=True, null=True, verbose_name="淨利率"),
                ),
                (
                    "EPS",
                    models.FloatField(
                        blank=True, null=True, verbose_name="基本每股盈餘 (EPS)"
                    ),
                ),
                (
                    "經營安全邊際",
                    models.FloatField(
                        blank=True, null=True, verbose_name="經營安全邊際"
                    ),
                ),
                (
                    "ROE",
                    models.FloatField(
                        blank=True, null=True, verbose_name="股東權益報酬率 (ROE)"
                    ),
                ),
                (
                    "財務槓桿",
                    models.FloatField(blank=True, null=True, verbose_name="財務槓桿"),
                ),
                (
                    "應收帳款收現日",
                    models.FloatField(
                        blank=True, null=True, verbose_name="應收帳款收現日"
                    ),
                ),
                (
                    "銷貨天數",
                    models.FloatField(blank=True, null=True, verbose_name="銷貨天數"),
                ),
                (
                    "加分項",
                    models.FloatField(blank=True, null=True, verbose_name="加分項"),
                ),
            ],
            options={
                "db_table": "stockMetrics",
            },
        ),
    ]
