# Generated by Django 5.0.6 on 2024-10-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.URLField(blank=True, max_length=500, null=True)),
                ("link", models.URLField(max_length=500)),
                ("content", models.TextField()),
                ("source", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "news",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_code", models.CharField(max_length=10, unique=True)),
                ("B", models.TextField()),
                ("P", models.TextField()),
                ("C", models.TextField()),
            ],
            options={
                "db_table": "stock",
            },
        ),
    ]
