<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-10-13 17:45
=======
# Generated by Django 5.0.7 on 2024-10-13 16:38
>>>>>>> e5f2fa3c886fafa03618accbda8b05b4047be31f

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD
    dependencies = [
        ("mylab", "0002_news"),
=======

    dependencies = [
        ('mylab', '0002_news'),
>>>>>>> e5f2fa3c886fafa03618accbda8b05b4047be31f
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="news",
            name="image",
=======
            model_name='news',
            name='image',
>>>>>>> e5f2fa3c886fafa03618accbda8b05b4047be31f
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
