# Generated by Django 5.0.7 on 2024-10-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
