# Generated by Django 5.0.6 on 2024-10-16 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mylab", "0002_stockmetrics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockmetrics",
            name="cash_and_cash_equivalents",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="current_assets",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="current_liabilities",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="inventory",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="net_accounts_receivable",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="net_profit_loss",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="non_current_assets",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="non_current_liabilities",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="total_assets",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="total_equity",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="total_liabilities",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="total_operating_income",
        ),
    ]
