# Generated by Django 5.0.6 on 2024-10-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mylab", "0003_remove_stockmetrics_cash_and_cash_equivalents_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockmetrics",
            name="accounts_receivable_days",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="cash_adequacy_ratio",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="cash_dividends",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="cash_flow_ratio",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="cash_reinvestment_ratio",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="cash_to_assets_ratio",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="financial_leverage",
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="eps",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="基本每股盈餘 (EPS)",
            ),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="gross_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="毛利率",
            ),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="net_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="淨利率",
            ),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="operating_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="營業利益率",
            ),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="operating_safety_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="經營安全邊際",
            ),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="roe",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="股東權益報酬率 (ROE)",
            ),
        ),
    ]
