# Generated by Django 5.0.6 on 2024-10-14 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mylab", "0003_news_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="image",
        ),
    ]
