# Generated by Django 5.0.6 on 2024-10-17 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mylab", "0004_remove_stockmetrics_accounts_receivable_days_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockmetrics",
            old_name="eps",
            new_name="EPS",
        ),
        migrations.RenameField(
            model_name="stockmetrics",
            old_name="roe",
            new_name="ROE",
        ),
        migrations.RenameField(
            model_name="stockmetrics",
            old_name="gross_margin",
            new_name="毛利率",
        ),
        migrations.RenameField(
            model_name="stockmetrics",
            old_name="net_margin",
            new_name="淨利率",
        ),
        migrations.RenameField(
            model_name="stockmetrics",
            old_name="operating_margin",
            new_name="營業利益率",
        ),
        migrations.RenameField(
            model_name="stockmetrics",
            old_name="operating_safety_margin",
            new_name="經營安全邊際",
        ),
    ]
