# Generated by Django 5.0.6 on 2024-10-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mylab", "0005_rename_eps_stockmetrics_eps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmetrics",
            name="加分項",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="加分項",
            ),
        ),
        migrations.AddField(
            model_name="stockmetrics",
            name="應收帳款收現日",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="應收帳款收現日",
            ),
        ),
        migrations.AddField(
            model_name="stockmetrics",
            name="現金允當比率",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="現金允當比率",
            ),
        ),
        migrations.AddField(
            model_name="stockmetrics",
            name="現金再投資比率",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="現金再投資比率",
            ),
        ),
        migrations.AddField(
            model_name="stockmetrics",
            name="現金流量比率",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="現金流量比率",
            ),
        ),
        migrations.AddField(
            model_name="stockmetrics",
            name="財務槓桿",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="財務槓桿",
            ),
        ),
        migrations.AddField(
            model_name="stockmetrics",
            name="銷貨天數",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="銷貨天數",
            ),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="ROE",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="股東權益報酬率 (ROE",
            ),
        ),
    ]
