# Generated by Django 5.0.6 on 2024-10-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mylab", "0006_stockmetrics_加分項_stockmetrics_應收帳款收現日_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmetrics",
            name="現金流量表分數",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="現金流量表分數",
            ),
        ),
        migrations.AddField(
            model_name="stockmetrics",
            name="綜合損益表分數",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="綜合損益表分數",
            ),
        ),
    ]
