# Generated by Django 5.0.6 on 2024-10-17 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mylab", "0007_stockmetrics_現金流量表分數_stockmetrics_綜合損益表分數"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockmetrics",
            name="現金流量表分數",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="綜合損益表分數",
        ),
    ]
