# Generated by Django 5.0.6 on 2024-10-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mylab", "0008_remove_stockmetrics_現金流量表分數_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmetrics",
            name="EPS",
            field=models.FloatField(blank=True, null=True, verbose_name="基本每股盈餘 (EPS)"),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="ROE",
            field=models.FloatField(
                blank=True, null=True, verbose_name="股東權益報酬率 (ROE)"
            ),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="加分項",
            field=models.FloatField(blank=True, null=True, verbose_name="加分項"),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="應收帳款收現日",
            field=models.FloatField(blank=True, null=True, verbose_name="應收帳款收現日"),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="毛利率",
            field=models.FloatField(blank=True, null=True, verbose_name="毛利率"),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="淨利率",
            field=models.FloatField(blank=True, null=True, verbose_name="淨利率"),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="營業利益率",
            field=models.FloatField(blank=True, null=True, verbose_name="營業利益率"),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="現金允當比率",
            field=models.FloatField(blank=True, null=True, verbose_name="現金允當比率"),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="現金再投資比率",
            field=models.FloatField(blank=True, null=True, verbose_name="現金再投資比率"),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="現金流量比率",
            field=models.FloatField(blank=True, null=True, verbose_name="現金流量比率"),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="經營安全邊際",
            field=models.FloatField(blank=True, null=True, verbose_name="經營安全邊際"),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="財務槓桿",
            field=models.FloatField(blank=True, null=True, verbose_name="財務槓桿"),
        ),
        migrations.AlterField(
            model_name="stockmetrics",
            name="銷貨天數",
            field=models.FloatField(blank=True, null=True, verbose_name="銷貨天數"),
        ),
    ]
