# Generated by Django 5.0.6 on 2024-10-19 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mylab", "0009_alter_stockmetrics_eps_alter_stockmetrics_roe_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockmetrics",
            name="現金允當比率",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="現金再投資比率",
        ),
        migrations.RemoveField(
            model_name="stockmetrics",
            name="現金流量比率",
        ),
    ]
