# Generated by Django 5.0.6 on 2024-11-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mylab", "0010_remove_stockmetrics_現金允當比率_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="region",
            field=models.CharField(default="未知", max_length=2),
        ),
    ]
