# Generated by Django 5.1.3 on 2024-12-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mylab", "0013_rename_title_news_event_news_daily_records_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="event",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="news",
            name="daily_records",
        ),
        migrations.RemoveField(
            model_name="news",
            name="disaster",
        ),
        migrations.RemoveField(
            model_name="news",
            name="links",
        ),
        migrations.RemoveField(
            model_name="news",
            name="location",
        ),
        migrations.RemoveField(
            model_name="news",
            name="recent_update",
        ),
        migrations.RemoveField(
            model_name="news",
            name="summary",
        ),
        migrations.AlterField(
            model_name="news",
            name="date",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="news",
            name="region",
            field=models.CharField(default="未知", max_length=2),
        ),
    ]
