# Generated by Django 5.0.6 on 2024-07-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_code", models.CharField(max_length=10, unique=True)),
                ("B", models.TextField()),
                ("P", models.TextField()),
                ("C", models.TextField()),
            ],
            options={
                "db_table": "stock",
            },
        ),
    ]
